// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	token "github.com/tgfukuda/be-master/token"
)

// Maker is an autogenerated mock type for the Maker type
type Maker struct {
	mock.Mock
}

type Maker_Expecter struct {
	mock *mock.Mock
}

func (_m *Maker) EXPECT() *Maker_Expecter {
	return &Maker_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function with given fields: username, duration
func (_m *Maker) CreateToken(username string, duration time.Duration) (string, *token.Payload, error) {
	ret := _m.Called(username, duration)

	var r0 string
	var r1 *token.Payload
	var r2 error
	if rf, ok := ret.Get(0).(func(string, time.Duration) (string, *token.Payload, error)); ok {
		return rf(username, duration)
	}
	if rf, ok := ret.Get(0).(func(string, time.Duration) string); ok {
		r0 = rf(username, duration)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, time.Duration) *token.Payload); ok {
		r1 = rf(username, duration)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*token.Payload)
		}
	}

	if rf, ok := ret.Get(2).(func(string, time.Duration) error); ok {
		r2 = rf(username, duration)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Maker_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type Maker_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//  - username string
//  - duration time.Duration
func (_e *Maker_Expecter) CreateToken(username interface{}, duration interface{}) *Maker_CreateToken_Call {
	return &Maker_CreateToken_Call{Call: _e.mock.On("CreateToken", username, duration)}
}

func (_c *Maker_CreateToken_Call) Run(run func(username string, duration time.Duration)) *Maker_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *Maker_CreateToken_Call) Return(_a0 string, _a1 *token.Payload, _a2 error) *Maker_CreateToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Maker_CreateToken_Call) RunAndReturn(run func(string, time.Duration) (string, *token.Payload, error)) *Maker_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function with given fields: _a0
func (_m *Maker) VerifyToken(_a0 string) (*token.Payload, error) {
	ret := _m.Called(_a0)

	var r0 *token.Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*token.Payload, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *token.Payload); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.Payload)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Maker_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type Maker_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//  - _a0 string
func (_e *Maker_Expecter) VerifyToken(_a0 interface{}) *Maker_VerifyToken_Call {
	return &Maker_VerifyToken_Call{Call: _e.mock.On("VerifyToken", _a0)}
}

func (_c *Maker_VerifyToken_Call) Run(run func(_a0 string)) *Maker_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Maker_VerifyToken_Call) Return(_a0 *token.Payload, _a1 error) *Maker_VerifyToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Maker_VerifyToken_Call) RunAndReturn(run func(string) (*token.Payload, error)) *Maker_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMaker creates a new instance of Maker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Maker {
	mock := &Maker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
