// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/tgfukuda/be-master/db/sqlc"

	uuid "github.com/google/uuid"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

type Querier_Expecter struct {
	mock *mock.Mock
}

func (_m *Querier) EXPECT() *Querier_Expecter {
	return &Querier_Expecter{mock: &_m.Mock}
}

// AddAccountBalance provides a mock function with given fields: ctx, arg
func (_m *Querier) AddAccountBalance(ctx context.Context, arg db.AddAccountBalanceParams) (db.Account, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.AddAccountBalanceParams) (db.Account, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.AddAccountBalanceParams) db.Account); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.AddAccountBalanceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_AddAccountBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAccountBalance'
type Querier_AddAccountBalance_Call struct {
	*mock.Call
}

// AddAccountBalance is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.AddAccountBalanceParams
func (_e *Querier_Expecter) AddAccountBalance(ctx interface{}, arg interface{}) *Querier_AddAccountBalance_Call {
	return &Querier_AddAccountBalance_Call{Call: _e.mock.On("AddAccountBalance", ctx, arg)}
}

func (_c *Querier_AddAccountBalance_Call) Run(run func(ctx context.Context, arg db.AddAccountBalanceParams)) *Querier_AddAccountBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.AddAccountBalanceParams))
	})
	return _c
}

func (_c *Querier_AddAccountBalance_Call) Return(_a0 db.Account, _a1 error) *Querier_AddAccountBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_AddAccountBalance_Call) RunAndReturn(run func(context.Context, db.AddAccountBalanceParams) (db.Account, error)) *Querier_AddAccountBalance_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccount provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateAccount(ctx context.Context, arg db.CreateAccountParams) (db.Account, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateAccountParams) (db.Account, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateAccountParams) db.Account); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateAccountParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type Querier_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.CreateAccountParams
func (_e *Querier_Expecter) CreateAccount(ctx interface{}, arg interface{}) *Querier_CreateAccount_Call {
	return &Querier_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, arg)}
}

func (_c *Querier_CreateAccount_Call) Run(run func(ctx context.Context, arg db.CreateAccountParams)) *Querier_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateAccountParams))
	})
	return _c
}

func (_c *Querier_CreateAccount_Call) Return(_a0 db.Account, _a1 error) *Querier_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateAccount_Call) RunAndReturn(run func(context.Context, db.CreateAccountParams) (db.Account, error)) *Querier_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEntry provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateEntry(ctx context.Context, arg db.CreateEntryParams) (db.Entry, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateEntryParams) (db.Entry, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateEntryParams) db.Entry); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Entry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateEntryParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEntry'
type Querier_CreateEntry_Call struct {
	*mock.Call
}

// CreateEntry is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.CreateEntryParams
func (_e *Querier_Expecter) CreateEntry(ctx interface{}, arg interface{}) *Querier_CreateEntry_Call {
	return &Querier_CreateEntry_Call{Call: _e.mock.On("CreateEntry", ctx, arg)}
}

func (_c *Querier_CreateEntry_Call) Run(run func(ctx context.Context, arg db.CreateEntryParams)) *Querier_CreateEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateEntryParams))
	})
	return _c
}

func (_c *Querier_CreateEntry_Call) Return(_a0 db.Entry, _a1 error) *Querier_CreateEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateEntry_Call) RunAndReturn(run func(context.Context, db.CreateEntryParams) (db.Entry, error)) *Querier_CreateEntry_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNewSession provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateNewSession(ctx context.Context, arg db.CreateNewSessionParams) (db.Session, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateNewSessionParams) (db.Session, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateNewSessionParams) db.Session); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateNewSessionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateNewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewSession'
type Querier_CreateNewSession_Call struct {
	*mock.Call
}

// CreateNewSession is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.CreateNewSessionParams
func (_e *Querier_Expecter) CreateNewSession(ctx interface{}, arg interface{}) *Querier_CreateNewSession_Call {
	return &Querier_CreateNewSession_Call{Call: _e.mock.On("CreateNewSession", ctx, arg)}
}

func (_c *Querier_CreateNewSession_Call) Run(run func(ctx context.Context, arg db.CreateNewSessionParams)) *Querier_CreateNewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateNewSessionParams))
	})
	return _c
}

func (_c *Querier_CreateNewSession_Call) Return(_a0 db.Session, _a1 error) *Querier_CreateNewSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateNewSession_Call) RunAndReturn(run func(context.Context, db.CreateNewSessionParams) (db.Session, error)) *Querier_CreateNewSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransfer provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateTransfer(ctx context.Context, arg db.CreateTransferParams) (db.Transfer, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateTransferParams) (db.Transfer, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateTransferParams) db.Transfer); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Transfer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateTransferParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransfer'
type Querier_CreateTransfer_Call struct {
	*mock.Call
}

// CreateTransfer is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.CreateTransferParams
func (_e *Querier_Expecter) CreateTransfer(ctx interface{}, arg interface{}) *Querier_CreateTransfer_Call {
	return &Querier_CreateTransfer_Call{Call: _e.mock.On("CreateTransfer", ctx, arg)}
}

func (_c *Querier_CreateTransfer_Call) Run(run func(ctx context.Context, arg db.CreateTransferParams)) *Querier_CreateTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateTransferParams))
	})
	return _c
}

func (_c *Querier_CreateTransfer_Call) Return(_a0 db.Transfer, _a1 error) *Querier_CreateTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateTransfer_Call) RunAndReturn(run func(context.Context, db.CreateTransferParams) (db.Transfer, error)) *Querier_CreateTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Querier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.CreateUserParams
func (_e *Querier_Expecter) CreateUser(ctx interface{}, arg interface{}) *Querier_CreateUser_Call {
	return &Querier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *Querier_CreateUser_Call) Run(run func(ctx context.Context, arg db.CreateUserParams)) *Querier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUserParams))
	})
	return _c
}

func (_c *Querier_CreateUser_Call) Return(_a0 db.User, _a1 error) *Querier_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateUser_Call) RunAndReturn(run func(context.Context, db.CreateUserParams) (db.User, error)) *Querier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVerifyEmail provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateVerifyEmail(ctx context.Context, arg db.CreateVerifyEmailParams) (db.VerifyEmail, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.VerifyEmail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateVerifyEmailParams) (db.VerifyEmail, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateVerifyEmailParams) db.VerifyEmail); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.VerifyEmail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateVerifyEmailParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateVerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVerifyEmail'
type Querier_CreateVerifyEmail_Call struct {
	*mock.Call
}

// CreateVerifyEmail is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.CreateVerifyEmailParams
func (_e *Querier_Expecter) CreateVerifyEmail(ctx interface{}, arg interface{}) *Querier_CreateVerifyEmail_Call {
	return &Querier_CreateVerifyEmail_Call{Call: _e.mock.On("CreateVerifyEmail", ctx, arg)}
}

func (_c *Querier_CreateVerifyEmail_Call) Run(run func(ctx context.Context, arg db.CreateVerifyEmailParams)) *Querier_CreateVerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateVerifyEmailParams))
	})
	return _c
}

func (_c *Querier_CreateVerifyEmail_Call) Return(_a0 db.VerifyEmail, _a1 error) *Querier_CreateVerifyEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateVerifyEmail_Call) RunAndReturn(run func(context.Context, db.CreateVerifyEmailParams) (db.VerifyEmail, error)) *Querier_CreateVerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteAccount(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type Querier_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//  - ctx context.Context
//  - id int64
func (_e *Querier_Expecter) DeleteAccount(ctx interface{}, id interface{}) *Querier_DeleteAccount_Call {
	return &Querier_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, id)}
}

func (_c *Querier_DeleteAccount_Call) Run(run func(ctx context.Context, id int64)) *Querier_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_DeleteAccount_Call) Return(_a0 error) *Querier_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_DeleteAccount_Call) RunAndReturn(run func(context.Context, int64) error) *Querier_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEntry provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteEntry(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_DeleteEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntry'
type Querier_DeleteEntry_Call struct {
	*mock.Call
}

// DeleteEntry is a helper method to define mock.On call
//  - ctx context.Context
//  - id int64
func (_e *Querier_Expecter) DeleteEntry(ctx interface{}, id interface{}) *Querier_DeleteEntry_Call {
	return &Querier_DeleteEntry_Call{Call: _e.mock.On("DeleteEntry", ctx, id)}
}

func (_c *Querier_DeleteEntry_Call) Run(run func(ctx context.Context, id int64)) *Querier_DeleteEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_DeleteEntry_Call) Return(_a0 error) *Querier_DeleteEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_DeleteEntry_Call) RunAndReturn(run func(context.Context, int64) error) *Querier_DeleteEntry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTransfer provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteTransfer(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_DeleteTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTransfer'
type Querier_DeleteTransfer_Call struct {
	*mock.Call
}

// DeleteTransfer is a helper method to define mock.On call
//  - ctx context.Context
//  - id int64
func (_e *Querier_Expecter) DeleteTransfer(ctx interface{}, id interface{}) *Querier_DeleteTransfer_Call {
	return &Querier_DeleteTransfer_Call{Call: _e.mock.On("DeleteTransfer", ctx, id)}
}

func (_c *Querier_DeleteTransfer_Call) Run(run func(ctx context.Context, id int64)) *Querier_DeleteTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_DeleteTransfer_Call) Return(_a0 error) *Querier_DeleteTransfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_DeleteTransfer_Call) RunAndReturn(run func(context.Context, int64) error) *Querier_DeleteTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, id
func (_m *Querier) GetAccount(ctx context.Context, id int64) (db.Account, error) {
	ret := _m.Called(ctx, id)

	var r0 db.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.Account); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type Querier_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//  - ctx context.Context
//  - id int64
func (_e *Querier_Expecter) GetAccount(ctx interface{}, id interface{}) *Querier_GetAccount_Call {
	return &Querier_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, id)}
}

func (_c *Querier_GetAccount_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetAccount_Call) Return(_a0 db.Account, _a1 error) *Querier_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetAccount_Call) RunAndReturn(run func(context.Context, int64) (db.Account, error)) *Querier_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountForUpdate provides a mock function with given fields: ctx, id
func (_m *Querier) GetAccountForUpdate(ctx context.Context, id int64) (db.Account, error) {
	ret := _m.Called(ctx, id)

	var r0 db.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.Account); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetAccountForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountForUpdate'
type Querier_GetAccountForUpdate_Call struct {
	*mock.Call
}

// GetAccountForUpdate is a helper method to define mock.On call
//  - ctx context.Context
//  - id int64
func (_e *Querier_Expecter) GetAccountForUpdate(ctx interface{}, id interface{}) *Querier_GetAccountForUpdate_Call {
	return &Querier_GetAccountForUpdate_Call{Call: _e.mock.On("GetAccountForUpdate", ctx, id)}
}

func (_c *Querier_GetAccountForUpdate_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetAccountForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetAccountForUpdate_Call) Return(_a0 db.Account, _a1 error) *Querier_GetAccountForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetAccountForUpdate_Call) RunAndReturn(run func(context.Context, int64) (db.Account, error)) *Querier_GetAccountForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountForUpdateUnsafe provides a mock function with given fields: ctx, id
func (_m *Querier) GetAccountForUpdateUnsafe(ctx context.Context, id int64) (db.Account, error) {
	ret := _m.Called(ctx, id)

	var r0 db.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.Account); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetAccountForUpdateUnsafe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountForUpdateUnsafe'
type Querier_GetAccountForUpdateUnsafe_Call struct {
	*mock.Call
}

// GetAccountForUpdateUnsafe is a helper method to define mock.On call
//  - ctx context.Context
//  - id int64
func (_e *Querier_Expecter) GetAccountForUpdateUnsafe(ctx interface{}, id interface{}) *Querier_GetAccountForUpdateUnsafe_Call {
	return &Querier_GetAccountForUpdateUnsafe_Call{Call: _e.mock.On("GetAccountForUpdateUnsafe", ctx, id)}
}

func (_c *Querier_GetAccountForUpdateUnsafe_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetAccountForUpdateUnsafe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetAccountForUpdateUnsafe_Call) Return(_a0 db.Account, _a1 error) *Querier_GetAccountForUpdateUnsafe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetAccountForUpdateUnsafe_Call) RunAndReturn(run func(context.Context, int64) (db.Account, error)) *Querier_GetAccountForUpdateUnsafe_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntry provides a mock function with given fields: ctx, id
func (_m *Querier) GetEntry(ctx context.Context, id int64) (db.Entry, error) {
	ret := _m.Called(ctx, id)

	var r0 db.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.Entry, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.Entry); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Entry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntry'
type Querier_GetEntry_Call struct {
	*mock.Call
}

// GetEntry is a helper method to define mock.On call
//  - ctx context.Context
//  - id int64
func (_e *Querier_Expecter) GetEntry(ctx interface{}, id interface{}) *Querier_GetEntry_Call {
	return &Querier_GetEntry_Call{Call: _e.mock.On("GetEntry", ctx, id)}
}

func (_c *Querier_GetEntry_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetEntry_Call) Return(_a0 db.Entry, _a1 error) *Querier_GetEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetEntry_Call) RunAndReturn(run func(context.Context, int64) (db.Entry, error)) *Querier_GetEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, id
func (_m *Querier) GetSession(ctx context.Context, id uuid.UUID) (db.Session, error) {
	ret := _m.Called(ctx, id)

	var r0 db.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.Session, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.Session); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type Querier_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//  - ctx context.Context
//  - id uuid.UUID
func (_e *Querier_Expecter) GetSession(ctx interface{}, id interface{}) *Querier_GetSession_Call {
	return &Querier_GetSession_Call{Call: _e.mock.On("GetSession", ctx, id)}
}

func (_c *Querier_GetSession_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Querier_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Querier_GetSession_Call) Return(_a0 db.Session, _a1 error) *Querier_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetSession_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.Session, error)) *Querier_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransfer provides a mock function with given fields: ctx, id
func (_m *Querier) GetTransfer(ctx context.Context, id int64) (db.Transfer, error) {
	ret := _m.Called(ctx, id)

	var r0 db.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.Transfer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.Transfer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Transfer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransfer'
type Querier_GetTransfer_Call struct {
	*mock.Call
}

// GetTransfer is a helper method to define mock.On call
//  - ctx context.Context
//  - id int64
func (_e *Querier_Expecter) GetTransfer(ctx interface{}, id interface{}) *Querier_GetTransfer_Call {
	return &Querier_GetTransfer_Call{Call: _e.mock.On("GetTransfer", ctx, id)}
}

func (_c *Querier_GetTransfer_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetTransfer_Call) Return(_a0 db.Transfer, _a1 error) *Querier_GetTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetTransfer_Call) RunAndReturn(run func(context.Context, int64) (db.Transfer, error)) *Querier_GetTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, username
func (_m *Querier) GetUser(ctx context.Context, username string) (db.User, error) {
	ret := _m.Called(ctx, username)

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type Querier_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//  - ctx context.Context
//  - username string
func (_e *Querier_Expecter) GetUser(ctx interface{}, username interface{}) *Querier_GetUser_Call {
	return &Querier_GetUser_Call{Call: _e.mock.On("GetUser", ctx, username)}
}

func (_c *Querier_GetUser_Call) Run(run func(ctx context.Context, username string)) *Querier_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetUser_Call) Return(_a0 db.User, _a1 error) *Querier_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetUser_Call) RunAndReturn(run func(context.Context, string) (db.User, error)) *Querier_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function with given fields: ctx, arg
func (_m *Querier) ListAccounts(ctx context.Context, arg db.ListAccountsParams) ([]db.Account, error) {
	ret := _m.Called(ctx, arg)

	var r0 []db.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListAccountsParams) ([]db.Account, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListAccountsParams) []db.Account); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListAccountsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type Querier_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.ListAccountsParams
func (_e *Querier_Expecter) ListAccounts(ctx interface{}, arg interface{}) *Querier_ListAccounts_Call {
	return &Querier_ListAccounts_Call{Call: _e.mock.On("ListAccounts", ctx, arg)}
}

func (_c *Querier_ListAccounts_Call) Run(run func(ctx context.Context, arg db.ListAccountsParams)) *Querier_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListAccountsParams))
	})
	return _c
}

func (_c *Querier_ListAccounts_Call) Return(_a0 []db.Account, _a1 error) *Querier_ListAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_ListAccounts_Call) RunAndReturn(run func(context.Context, db.ListAccountsParams) ([]db.Account, error)) *Querier_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// ListEntries provides a mock function with given fields: ctx, arg
func (_m *Querier) ListEntries(ctx context.Context, arg db.ListEntriesParams) ([]db.Entry, error) {
	ret := _m.Called(ctx, arg)

	var r0 []db.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListEntriesParams) ([]db.Entry, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListEntriesParams) []db.Entry); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListEntriesParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_ListEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEntries'
type Querier_ListEntries_Call struct {
	*mock.Call
}

// ListEntries is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.ListEntriesParams
func (_e *Querier_Expecter) ListEntries(ctx interface{}, arg interface{}) *Querier_ListEntries_Call {
	return &Querier_ListEntries_Call{Call: _e.mock.On("ListEntries", ctx, arg)}
}

func (_c *Querier_ListEntries_Call) Run(run func(ctx context.Context, arg db.ListEntriesParams)) *Querier_ListEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListEntriesParams))
	})
	return _c
}

func (_c *Querier_ListEntries_Call) Return(_a0 []db.Entry, _a1 error) *Querier_ListEntries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_ListEntries_Call) RunAndReturn(run func(context.Context, db.ListEntriesParams) ([]db.Entry, error)) *Querier_ListEntries_Call {
	_c.Call.Return(run)
	return _c
}

// ListEntriesOf provides a mock function with given fields: ctx, arg
func (_m *Querier) ListEntriesOf(ctx context.Context, arg db.ListEntriesOfParams) ([]db.Entry, error) {
	ret := _m.Called(ctx, arg)

	var r0 []db.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListEntriesOfParams) ([]db.Entry, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListEntriesOfParams) []db.Entry); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListEntriesOfParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_ListEntriesOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEntriesOf'
type Querier_ListEntriesOf_Call struct {
	*mock.Call
}

// ListEntriesOf is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.ListEntriesOfParams
func (_e *Querier_Expecter) ListEntriesOf(ctx interface{}, arg interface{}) *Querier_ListEntriesOf_Call {
	return &Querier_ListEntriesOf_Call{Call: _e.mock.On("ListEntriesOf", ctx, arg)}
}

func (_c *Querier_ListEntriesOf_Call) Run(run func(ctx context.Context, arg db.ListEntriesOfParams)) *Querier_ListEntriesOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListEntriesOfParams))
	})
	return _c
}

func (_c *Querier_ListEntriesOf_Call) Return(_a0 []db.Entry, _a1 error) *Querier_ListEntriesOf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_ListEntriesOf_Call) RunAndReturn(run func(context.Context, db.ListEntriesOfParams) ([]db.Entry, error)) *Querier_ListEntriesOf_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransfers provides a mock function with given fields: ctx, arg
func (_m *Querier) ListTransfers(ctx context.Context, arg db.ListTransfersParams) ([]db.Transfer, error) {
	ret := _m.Called(ctx, arg)

	var r0 []db.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListTransfersParams) ([]db.Transfer, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListTransfersParams) []db.Transfer); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListTransfersParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_ListTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransfers'
type Querier_ListTransfers_Call struct {
	*mock.Call
}

// ListTransfers is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.ListTransfersParams
func (_e *Querier_Expecter) ListTransfers(ctx interface{}, arg interface{}) *Querier_ListTransfers_Call {
	return &Querier_ListTransfers_Call{Call: _e.mock.On("ListTransfers", ctx, arg)}
}

func (_c *Querier_ListTransfers_Call) Run(run func(ctx context.Context, arg db.ListTransfersParams)) *Querier_ListTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListTransfersParams))
	})
	return _c
}

func (_c *Querier_ListTransfers_Call) Return(_a0 []db.Transfer, _a1 error) *Querier_ListTransfers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_ListTransfers_Call) RunAndReturn(run func(context.Context, db.ListTransfersParams) ([]db.Transfer, error)) *Querier_ListTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransfersFrom provides a mock function with given fields: ctx, arg
func (_m *Querier) ListTransfersFrom(ctx context.Context, arg db.ListTransfersFromParams) ([]db.Transfer, error) {
	ret := _m.Called(ctx, arg)

	var r0 []db.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListTransfersFromParams) ([]db.Transfer, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListTransfersFromParams) []db.Transfer); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListTransfersFromParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_ListTransfersFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransfersFrom'
type Querier_ListTransfersFrom_Call struct {
	*mock.Call
}

// ListTransfersFrom is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.ListTransfersFromParams
func (_e *Querier_Expecter) ListTransfersFrom(ctx interface{}, arg interface{}) *Querier_ListTransfersFrom_Call {
	return &Querier_ListTransfersFrom_Call{Call: _e.mock.On("ListTransfersFrom", ctx, arg)}
}

func (_c *Querier_ListTransfersFrom_Call) Run(run func(ctx context.Context, arg db.ListTransfersFromParams)) *Querier_ListTransfersFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListTransfersFromParams))
	})
	return _c
}

func (_c *Querier_ListTransfersFrom_Call) Return(_a0 []db.Transfer, _a1 error) *Querier_ListTransfersFrom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_ListTransfersFrom_Call) RunAndReturn(run func(context.Context, db.ListTransfersFromParams) ([]db.Transfer, error)) *Querier_ListTransfersFrom_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransfersTo provides a mock function with given fields: ctx, arg
func (_m *Querier) ListTransfersTo(ctx context.Context, arg db.ListTransfersToParams) ([]db.Transfer, error) {
	ret := _m.Called(ctx, arg)

	var r0 []db.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListTransfersToParams) ([]db.Transfer, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListTransfersToParams) []db.Transfer); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListTransfersToParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_ListTransfersTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransfersTo'
type Querier_ListTransfersTo_Call struct {
	*mock.Call
}

// ListTransfersTo is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.ListTransfersToParams
func (_e *Querier_Expecter) ListTransfersTo(ctx interface{}, arg interface{}) *Querier_ListTransfersTo_Call {
	return &Querier_ListTransfersTo_Call{Call: _e.mock.On("ListTransfersTo", ctx, arg)}
}

func (_c *Querier_ListTransfersTo_Call) Run(run func(ctx context.Context, arg db.ListTransfersToParams)) *Querier_ListTransfersTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListTransfersToParams))
	})
	return _c
}

func (_c *Querier_ListTransfersTo_Call) Return(_a0 []db.Transfer, _a1 error) *Querier_ListTransfersTo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_ListTransfersTo_Call) RunAndReturn(run func(context.Context, db.ListTransfersToParams) ([]db.Transfer, error)) *Querier_ListTransfersTo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateAccount(ctx context.Context, arg db.UpdateAccountParams) (db.Account, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateAccountParams) (db.Account, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateAccountParams) db.Account); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateAccountParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type Querier_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.UpdateAccountParams
func (_e *Querier_Expecter) UpdateAccount(ctx interface{}, arg interface{}) *Querier_UpdateAccount_Call {
	return &Querier_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", ctx, arg)}
}

func (_c *Querier_UpdateAccount_Call) Run(run func(ctx context.Context, arg db.UpdateAccountParams)) *Querier_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateAccountParams))
	})
	return _c
}

func (_c *Querier_UpdateAccount_Call) Return(_a0 db.Account, _a1 error) *Querier_UpdateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_UpdateAccount_Call) RunAndReturn(run func(context.Context, db.UpdateAccountParams) (db.Account, error)) *Querier_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEntry provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateEntry(ctx context.Context, arg db.UpdateEntryParams) (db.Entry, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateEntryParams) (db.Entry, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateEntryParams) db.Entry); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Entry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateEntryParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_UpdateEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEntry'
type Querier_UpdateEntry_Call struct {
	*mock.Call
}

// UpdateEntry is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.UpdateEntryParams
func (_e *Querier_Expecter) UpdateEntry(ctx interface{}, arg interface{}) *Querier_UpdateEntry_Call {
	return &Querier_UpdateEntry_Call{Call: _e.mock.On("UpdateEntry", ctx, arg)}
}

func (_c *Querier_UpdateEntry_Call) Run(run func(ctx context.Context, arg db.UpdateEntryParams)) *Querier_UpdateEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateEntryParams))
	})
	return _c
}

func (_c *Querier_UpdateEntry_Call) Return(_a0 db.Entry, _a1 error) *Querier_UpdateEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_UpdateEntry_Call) RunAndReturn(run func(context.Context, db.UpdateEntryParams) (db.Entry, error)) *Querier_UpdateEntry_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferAmount provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateTransferAmount(ctx context.Context, arg db.UpdateTransferAmountParams) (db.Transfer, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferAmountParams) (db.Transfer, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferAmountParams) db.Transfer); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Transfer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateTransferAmountParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_UpdateTransferAmount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferAmount'
type Querier_UpdateTransferAmount_Call struct {
	*mock.Call
}

// UpdateTransferAmount is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.UpdateTransferAmountParams
func (_e *Querier_Expecter) UpdateTransferAmount(ctx interface{}, arg interface{}) *Querier_UpdateTransferAmount_Call {
	return &Querier_UpdateTransferAmount_Call{Call: _e.mock.On("UpdateTransferAmount", ctx, arg)}
}

func (_c *Querier_UpdateTransferAmount_Call) Run(run func(ctx context.Context, arg db.UpdateTransferAmountParams)) *Querier_UpdateTransferAmount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferAmountParams))
	})
	return _c
}

func (_c *Querier_UpdateTransferAmount_Call) Return(_a0 db.Transfer, _a1 error) *Querier_UpdateTransferAmount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_UpdateTransferAmount_Call) RunAndReturn(run func(context.Context, db.UpdateTransferAmountParams) (db.Transfer, error)) *Querier_UpdateTransferAmount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferFrom provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateTransferFrom(ctx context.Context, arg db.UpdateTransferFromParams) (db.Transfer, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferFromParams) (db.Transfer, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferFromParams) db.Transfer); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Transfer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateTransferFromParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_UpdateTransferFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferFrom'
type Querier_UpdateTransferFrom_Call struct {
	*mock.Call
}

// UpdateTransferFrom is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.UpdateTransferFromParams
func (_e *Querier_Expecter) UpdateTransferFrom(ctx interface{}, arg interface{}) *Querier_UpdateTransferFrom_Call {
	return &Querier_UpdateTransferFrom_Call{Call: _e.mock.On("UpdateTransferFrom", ctx, arg)}
}

func (_c *Querier_UpdateTransferFrom_Call) Run(run func(ctx context.Context, arg db.UpdateTransferFromParams)) *Querier_UpdateTransferFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferFromParams))
	})
	return _c
}

func (_c *Querier_UpdateTransferFrom_Call) Return(_a0 db.Transfer, _a1 error) *Querier_UpdateTransferFrom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_UpdateTransferFrom_Call) RunAndReturn(run func(context.Context, db.UpdateTransferFromParams) (db.Transfer, error)) *Querier_UpdateTransferFrom_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferTo provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateTransferTo(ctx context.Context, arg db.UpdateTransferToParams) (db.Transfer, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferToParams) (db.Transfer, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferToParams) db.Transfer); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Transfer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateTransferToParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_UpdateTransferTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferTo'
type Querier_UpdateTransferTo_Call struct {
	*mock.Call
}

// UpdateTransferTo is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.UpdateTransferToParams
func (_e *Querier_Expecter) UpdateTransferTo(ctx interface{}, arg interface{}) *Querier_UpdateTransferTo_Call {
	return &Querier_UpdateTransferTo_Call{Call: _e.mock.On("UpdateTransferTo", ctx, arg)}
}

func (_c *Querier_UpdateTransferTo_Call) Run(run func(ctx context.Context, arg db.UpdateTransferToParams)) *Querier_UpdateTransferTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferToParams))
	})
	return _c
}

func (_c *Querier_UpdateTransferTo_Call) Return(_a0 db.Transfer, _a1 error) *Querier_UpdateTransferTo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_UpdateTransferTo_Call) RunAndReturn(run func(context.Context, db.UpdateTransferToParams) (db.Transfer, error)) *Querier_UpdateTransferTo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.User, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserParams) (db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserParams) db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type Querier_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.UpdateUserParams
func (_e *Querier_Expecter) UpdateUser(ctx interface{}, arg interface{}) *Querier_UpdateUser_Call {
	return &Querier_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, arg)}
}

func (_c *Querier_UpdateUser_Call) Run(run func(ctx context.Context, arg db.UpdateUserParams)) *Querier_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateUserParams))
	})
	return _c
}

func (_c *Querier_UpdateUser_Call) Return(_a0 db.User, _a1 error) *Querier_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_UpdateUser_Call) RunAndReturn(run func(context.Context, db.UpdateUserParams) (db.User, error)) *Querier_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVerifyEmail provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateVerifyEmail(ctx context.Context, arg db.UpdateVerifyEmailParams) (db.VerifyEmail, error) {
	ret := _m.Called(ctx, arg)

	var r0 db.VerifyEmail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateVerifyEmailParams) (db.VerifyEmail, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateVerifyEmailParams) db.VerifyEmail); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.VerifyEmail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateVerifyEmailParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_UpdateVerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVerifyEmail'
type Querier_UpdateVerifyEmail_Call struct {
	*mock.Call
}

// UpdateVerifyEmail is a helper method to define mock.On call
//  - ctx context.Context
//  - arg db.UpdateVerifyEmailParams
func (_e *Querier_Expecter) UpdateVerifyEmail(ctx interface{}, arg interface{}) *Querier_UpdateVerifyEmail_Call {
	return &Querier_UpdateVerifyEmail_Call{Call: _e.mock.On("UpdateVerifyEmail", ctx, arg)}
}

func (_c *Querier_UpdateVerifyEmail_Call) Run(run func(ctx context.Context, arg db.UpdateVerifyEmailParams)) *Querier_UpdateVerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateVerifyEmailParams))
	})
	return _c
}

func (_c *Querier_UpdateVerifyEmail_Call) Return(_a0 db.VerifyEmail, _a1 error) *Querier_UpdateVerifyEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_UpdateVerifyEmail_Call) RunAndReturn(run func(context.Context, db.UpdateVerifyEmailParams) (db.VerifyEmail, error)) *Querier_UpdateVerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
