// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	asynq "github.com/hibiken/asynq"

	mock "github.com/stretchr/testify/mock"

	worker "github.com/tgfukuda/be-master/worker"
)

// TaskDistributor is an autogenerated mock type for the TaskDistributor type
type TaskDistributor struct {
	mock.Mock
}

type TaskDistributor_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskDistributor) EXPECT() *TaskDistributor_Expecter {
	return &TaskDistributor_Expecter{mock: &_m.Mock}
}

// DistributeTaskSendVerifyEmail provides a mock function with given fields: ctx, payload, opts
func (_m *TaskDistributor) DistributeTaskSendVerifyEmail(ctx context.Context, payload *worker.PayloadSendVerifyEmail, opts ...asynq.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, payload)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *worker.PayloadSendVerifyEmail, ...asynq.Option) error); ok {
		r0 = rf(ctx, payload, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskDistributor_DistributeTaskSendVerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DistributeTaskSendVerifyEmail'
type TaskDistributor_DistributeTaskSendVerifyEmail_Call struct {
	*mock.Call
}

// DistributeTaskSendVerifyEmail is a helper method to define mock.On call
//  - ctx context.Context
//  - payload *worker.PayloadSendVerifyEmail
//  - opts ...asynq.Option
func (_e *TaskDistributor_Expecter) DistributeTaskSendVerifyEmail(ctx interface{}, payload interface{}, opts ...interface{}) *TaskDistributor_DistributeTaskSendVerifyEmail_Call {
	return &TaskDistributor_DistributeTaskSendVerifyEmail_Call{Call: _e.mock.On("DistributeTaskSendVerifyEmail",
		append([]interface{}{ctx, payload}, opts...)...)}
}

func (_c *TaskDistributor_DistributeTaskSendVerifyEmail_Call) Run(run func(ctx context.Context, payload *worker.PayloadSendVerifyEmail, opts ...asynq.Option)) *TaskDistributor_DistributeTaskSendVerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]asynq.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(asynq.Option)
			}
		}
		run(args[0].(context.Context), args[1].(*worker.PayloadSendVerifyEmail), variadicArgs...)
	})
	return _c
}

func (_c *TaskDistributor_DistributeTaskSendVerifyEmail_Call) Return(_a0 error) *TaskDistributor_DistributeTaskSendVerifyEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskDistributor_DistributeTaskSendVerifyEmail_Call) RunAndReturn(run func(context.Context, *worker.PayloadSendVerifyEmail, ...asynq.Option) error) *TaskDistributor_DistributeTaskSendVerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskDistributor creates a new instance of TaskDistributor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskDistributor(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskDistributor {
	mock := &TaskDistributor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
